### ISSUE TITLE
Problem loading the dataset

### ISSUE THREAD

**Issue by vatsal2473** [vatsal2473/mini_hackathon#3]
The dataset format was updated and now there is a problem loading the dataset in the both the notebooks
* Premise_classification_RoBERTa_baseline.ipynb
*  Stance_detection_RoBERTa_baseline.ipynb
- [x] fix this bug in code cell 4 and 7 of both the notebooks

**Comment by The1one1** [comment]
Has the dataset format changed from tsv to csv? If so, please assign this issue to me. I will update the code
